name: create-labels
on: [workflow_dispatch]
jobs:
  inspect-env:
    runs-on: ubuntu-latest
    steps:

      # Check out the repo
      - uses: actions/checkout@v2

      # Get the workflow id from the workflow name=$NAME
      - name: label_names
        id: label_names
        run: ./.github/scripts/git_api.sh
        shell: bash
        env:
          template: label_names

      # Get the set of formula names
      - name: formula_names
        id: formula_names
        run: ./.github/scripts/introspect.sh
        shell: bash
        env:
          template: formula_names

      # For debugging and troubleshooting - introspective environment audit
      - name: show_env
        run: ./.github/scripts/show_env.sh
        shell: bash
        env:
          CHECK_CREATE_LABELS: "${{ steps.formula_names.outputs.RESULT }}"
          EXISTING_LABELS: "${{ steps.label_names.outputs.RESULT }}"
          INSPECT_GROUPS: '
              git=GITHUB_ACTION,GITHUB_ACTIONS,GITHUB_ACTION_REF,GITHUB_ACTION_REPOSITORY,GITHUB_ACTOR,GITHUB_API_URL,GITHUB_BASE_REF,GITHUB_ENV,GITHUB_EVENT_NAME,GITHUB_EVENT_PATH,GITHUB_GRAPHQL_URL,GITHUB_HEAD_REF,GITHUB_JOB,GITHUB_PATH,GITHUB_REF,GITHUB_REPOSITORY,GITHUB_REPOSITORY_OWNER,GITHUB_RETENTION_DAYS,GITHUB_RUN_ID,GITHUB_RUN_NUMBER,GITHUB_SERVER_URL,GITHUB_SHA,GITHUB_WORKFLOW,GITHUB_WORKSPACE
              reference=EXISTING_LABELS,CHECK_CREATE_LABELS
            '

      # For debugging and troubleshooting - introspective environment audit
      - name: create_label
        run: ./.github/scripts/create_label.sh
        shell: bash
        env:
          CHECK_CREATE_LABELS: "${{ steps.formula_names.outputs.RESULT }}"
          EXISTING_LABELS: "${{ steps.formula_shas.outputs.RESULT }}"
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
