name: dev-wf
on: push
jobs:
  inspect-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Check out the repo

      - name: repo_workflow_completed_run_ids # Get the repository workflow id for the passed NAME
        id: repo_workflow_completed_run_ids
        run: ./.github/scripts/git_api.sh repo_workflow_completed_run_ids
        shell: bash

      # Inspect the parameters and environment before deleting each workflow run
      # THIS IS NOT MANDATORY - this step could be omitted entirely
      - name: show_env
        id: show_env
        run: ./.github/scripts/introspect.sh
        shell: bash
        env:
          template: show_env
          RUN_IDS: "${{ steps.repo_workflow_completed_run_ids.outputs.RESULT }}"
