name: dev-wf
on: push
jobs:
  inspect-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Check out the repo

      - name: repo_workflow_completed_run_ids # Get the repository workflow id for the passed NAME
        id: repo_workflow_completed_run_ids
        run: ./.github/scripts/git_api.sh repo_workflow_completed_run_ids
        shell: bash

      # Inspect the parameters and environment before deleting each workflow run
      - name: show_env
        id: show_env
        run: ./.github/scripts/introspect.sh show_env
        shell: bash
        env:
          RUN_IDS: "${{ steps.repo_workflow_completed_run_ids.outputs.RESULT }}"

      # - name: delete_workflow_run
      #   id: delete_workflow_run
      #   run: ./.github/scripts/git_api.sh delete_workflow_run
      #   shell: bash
      #   env:
      #     ID: "${{ steps.repo_workflow_completed_run_ids.outputs.RESULT }}"
      #     GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
