name: dev-wf
on: push
jobs:
  inspect-env:
    runs-on: ubuntu-latest
    steps:

      # Check out the repo
      - uses: actions/checkout@v2

      # Get the repository workflow id for the passed NAME
      - name: repo_workflow_completed_run_ids
        id: repo_workflow_completed_run_ids
        run: ./.github/scripts/git_api.sh repo_workflow_completed_run_ids
        shell: bash

      # Lists the files, directories modified in HEAD vs BASE
      - name: diff
        id: diff
        run: ./.github/scripts/diff_files.sh
        shell: bash

      # Inspect the parameters and environment before deleting each workflow run
      - name: show_env
        run: ./.github/scripts/introspect.sh show_env
        shell: bash
        env:
          RUN_IDS: "${{ steps.repo_workflow_completed_run_ids.outputs.RESULT }}"
          DIFF_OUT: "${{ steps.diff.outputs.OUTPUTS }}"
