
# Removes completed workflow runs (trigger manually from repo actions page)

name: flush-all-completed-workflow-runs

on: workflow_dispatch

jobs:
  inspect-env:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo
      - uses: actions/checkout@v2
      # Get the set of completed workflow run id's
      - name: repo_workflow_completed_run_ids
        id: repo_workflow_completed_run_ids
        run: ./.github/scripts/git_api.sh repo_workflow_completed_run_ids
        shell: bash
      # delete the workflow runs with ids found in 'repo_workflow_completed_run_ids'
      - name: delete_workflow_run
        run: ./.github/scripts/git_api.sh delete_workflow_run
        shell: bash
        env:
          ID: "${{ steps.repo_workflow_completed_run_ids.outputs.RESULT }}"
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
