name: bashtest
on: [push]
jobs:
  exec-bash-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install Rubocop gem
        run: gem install rubocop
      - name: 'action'
        run: ./.github/scripts/parseaction.sh
        shell: bash


# Event Triggers:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows

# Permissions:
# -----------------------------------------------------------------------------
# permissions:
#   actions: read|write|none
#   checks: read|write|none
#   contents: read|write|none
#   deployments: read|write|none
#   issues: read|write|none
#   packages: read|write|none
#   pull-requests: read|write|none
#   repository-projects: read|write|none
#   security-events: read|write|none
#   statuses: read|write|none

# Or you can specify for read/write all
# permissions: read-all|write-all
# -----------------------------------------------------------------------------


# ENV:
# -----------------------------------------------------------------------------
# env:
#   SERVER: production
# -----------------------------------------------------------------------------
