name: introspect
on: [workflow_dispatch]
jobs:
  inspect-env:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo
      - uses: actions/checkout@v2

      # Get the workflow id from the workflow name=$NAME
      - name: label_names
        id: label_names
        run: ./.github/scripts/git_api.sh label_names
        shell: bash

      # Get formula related metadata
      - name: formula_data
        id: formula_data
        run: ./.github/scripts/introspect.sh all
        shell: bash

      # For debugging and troubleshooting - introspective environment audit
      - name: show_env
        id: show_env
        run: ./.github/scripts/introspect.sh show_env
        shell: bash
        env:
          FORMULA_NAMES: "${{ steps.formula_data.outputs.FORMULA_NAMES }}"
          FORMULA_PATHS: "${{ steps.formula_data.outputs.FORMULA_PATHS }}"
          FORMULA_STABLE_SHAS: "${{ steps.formula_data.outputs.FORMULA_STABLE_SHAS }}"
          FORMULA_HEAD_SHAS: "${{ steps.formula_data.outputs.FORMULA_HEAD_SHAS }}"
          FORMULA_STABLE_URLS: "${{ steps.formula_data.outputs.FORMULA_STABLE_URLS }}"
          FORMULA_HEAD_URLS: "${{ steps.formula_data.outputs.FORMULA_HEAD_URLS }}"
          INSPECT_GROUPS: '
              git=GITHUB_ACTION,GITHUB_ACTIONS,GITHUB_ACTION_REF,GITHUB_ACTION_REPOSITORY,GITHUB_ACTOR,GITHUB_API_URL,GITHUB_BASE_REF,GITHUB_ENV,GITHUB_EVENT_NAME,GITHUB_EVENT_PATH,GITHUB_GRAPHQL_URL,GITHUB_HEAD_REF,GITHUB_JOB,GITHUB_PATH,GITHUB_REF,GITHUB_REPOSITORY,GITHUB_REPOSITORY_OWNER,GITHUB_RETENTION_DAYS,GITHUB_RUN_ID,GITHUB_RUN_NUMBER,GITHUB_SERVER_URL,GITHUB_SHA,GITHUB_WORKFLOW,GITHUB_WORKSPACE
              reference=FORMULA_NAMES,FORMULA_PATHS,FORMULA_SHAS,FORMULA_STABLE_URLS,FORMULA_HEAD_URLS
              formula=${{ steps.formula_data.outputs.OUTPUTS }}
            '
          LABEL_NAMES: "${{ steps.label_names.outputs.RESULT }}"
