---
name: Lint Code Base

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/super-linter

#############################
# Start the job on all push #
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:

      # Checkout the code base
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # Run Linter against code base
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
