name: main-check
on:
  push: # called push but also fires when merging
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  main-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install Rubocop gem
        run: gem install rubocop
      - name: parseaction
        run: .github/scripts/parseaction.sh
        shell: bash
