name: onpush
on: [push]
jobs:
  inspect-env:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo
      - uses: actions/checkout@v2
      - name: formula_data
        id: formula_data
        run: ./.github/scripts/introspect.sh
        shell: bash
        env:
          template: all
      - name: show_env
        run: ./.github/scripts/show_env.sh
        shell: bash
        env:
          FORMULA_NAMES: "${{ steps.formula_data.outputs.FORMULA_NAMES }}"
          FORMULA_PATHS: "${{ steps.formula_data.outputs.FORMULA_PATHS }}"
          FORMULA_STABLE_SHAS: "${{ steps.formula_data.outputs.FORMULA_STABLE_SHAS }}"
          FORMULA_HEAD_SHAS: "${{ steps.formula_data.outputs.FORMULA_HEAD_SHAS }}"
          FORMULA_STABLE_URLS: "${{ steps.formula_data.outputs.FORMULA_STABLE_URLS }}"
          FORMULA_HEAD_URLS: "${{ steps.formula_data.outputs.FORMULA_HEAD_URLS }}"
          FORMULA_FUNCTIONS: "${{ steps.formula_data.outputs.FUNCTIONS }}"
          INSPECT_GROUPS: '
              git=GITHUB_ACTION,GITHUB_ACTIONS,GITHUB_ACTION_REF,GITHUB_ACTION_REPOSITORY,GITHUB_ACTOR,GITHUB_API_URL,GITHUB_BASE_REF,GITHUB_ENV,GITHUB_EVENT_NAME,GITHUB_EVENT_PATH,GITHUB_GRAPHQL_URL,GITHUB_HEAD_REF,GITHUB_JOB,GITHUB_PATH,GITHUB_REF,GITHUB_REPOSITORY,GITHUB_REPOSITORY_OWNER,GITHUB_RETENTION_DAYS,GITHUB_RUN_ID,GITHUB_RUN_NUMBER,GITHUB_SERVER_URL,GITHUB_SHA,GITHUB_WORKFLOW,GITHUB_WORKSPACE
              formula=${{ steps.formula_data.outputs.OUTPUTS }}
            '
        # review=FORMULA_NAMES,FORMULA_PATHS,FORMULA_STABLE_SHAS,FORMULA_HEAD_SHAS,FORMULA_STABLE_URLS,FORMULA_HEAD_URLS

      # LABEL_NAMES: "${{ steps.label_names.outputs.RESULT }}"
      # - name: action_data
      #   id: action_data_1
      #   run: ./.github/scripts/action_data.sh
      #   shell: bash
      # - name: show_env
      #   id: show_env
      #   run: ./.github/scripts/show_env.sh
      #   shell: bash
      #   env:
      #     INSPECT_GROUPS: '
      #       git=GITHUB_ACTION,GITHUB_ACTIONS,GITHUB_ACTION_REF,GITHUB_ACTION_REPOSITORY,GITHUB_ACTOR,GITHUB_API_URL,GITHUB_BASE_REF,GITHUB_ENV,GITHUB_EVENT_NAME,GITHUB_EVENT_PATH,GITHUB_GRAPHQL_URL,GITHUB_HEAD_REF,GITHUB_JOB,GITHUB_PATH,GITHUB_REF,GITHUB_REPOSITORY,GITHUB_REPOSITORY_OWNER,GITHUB_RETENTION_DAYS,GITHUB_RUN_ID,GITHUB_RUN_NUMBER,GITHUB_SERVER_URL,GITHUB_SHA,GITHUB_WORKFLOW,GITHUB_WORKSPACE
      #       '
      # Get the workflow id from the workflow name=$NAME
      #      - name: label_names
      #        id: label_names
      #        run: ./.github/scripts/git_api.sh
      #        shell: bash
      #        env:
      #          template: label_names
      # Get list of formulas in this repo
      #      - name: formula_names
      #        id: formula_names
      #        run: ./.github/scripts/introspect.sh
      #        shell: bash
      #        env:
      #          template: formula_names
      #      # Get the set of formula names
      #      - name: formula_paths
      #        id: formula_paths
      #        run: ./.github/scripts/introspect.sh
      #        shell: bash
      #        env:
      #          template: formula_paths
      #      # Get the set of formula paths
      #      - name: formula_shas
      #        id: formula_shas
      #        run: ./.github/scripts/introspect.sh
      #        shell: bash
      #        env:
      #          template: formula_shas
      #      # Get the set of formula paths
      #      - name: formula_stable_urls
      #        id: formula_stable_urls
      #        run: ./.github/scripts/introspect.sh
      #        shell: bash
      #        env:
      #          template: formula_stable_urls
      #      # Get the set of formula paths
      #      - name: formula_head_urls
      #        id: formula_head_urls
      #        run: ./.github/scripts/introspect.sh
      #        shell: bash
      #        env:
      #          template: formula_head_urls
