name: pr-formula-tag
on: [pull_request]
env:
  COMPARE_BRANCH: main
jobs:
  inspect-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # List of labels for this repository
      - name: label_names
        id: label_names
        run: ./.github/scripts/git_api.sh
        shell: bash
        env:
          template: label_names

      # Lists the files, directories
      - id: diff
        name: diff
        run: ./.github/scripts/diff_files.sh
        shell: bash

      # Show the formula files that were changed in the HEAD vs the BASE branch
      - id: diff_formula
        name: diff_formula
        run: ./.github/scripts/diff_formula.sh
        shell: bash
        env:
          DIFF_FILES: "${{ steps.diff.outputs.DIFF_FILES }}"

      # Print the values from introspection
      - name: inspect_env
        run: ./.github/scripts/inspect_env.sh
        shell: bash
        env:
          # INTROSPECTION
          LABELS: ${{ steps.label_names.outputs.RESULT }}
          # DIFF
          DIFF_BRANCH: "${{ steps.diff.outputs.DIFF_BRANCH }}"
          DIFF_DIRS: "${{ steps.diff.outputs.DIFF_DIRS }}"
          DIFF_FILES: "${{ steps.diff.outputs.DIFF_FILES }}"
          # SPECIFIC
          DIFF_FORMULA: "${{ steps.diff_formula.outputs.DIFF_FORMULA }}"
          # INSPECT_ENV_FIELDS: "GITHUB_ACTION,GITHUB_ACTIONS,GITHUB_ACTION_REF,GITHUB_ACTION_REPOSITORY,GITHUB_ACTOR,GITHUB_API_URL,GITHUB_BASE_REF,GITHUB_ENV,GITHUB_EVENT_NAME,GITHUB_EVENT_PATH,GITHUB_GRAPHQL_URL,GITHUB_HEAD_REF,GITHUB_JOB,GITHUB_PATH,GITHUB_REF,GITHUB_REPOSITORY,GITHUB_REPOSITORY_OWNER,GITHUB_RETENTION_DAYS,GITHUB_RUN_ID,GITHUB_RUN_NUMBER,GITHUB_SERVER_URL,GITHUB_SHA,GITHUB_WORKFLOW,GITHUB_WORKSPACE"
          INSPECT_GROUPS: '
            git_env=GITHUB_ACTION,GITHUB_ACTIONS,GITHUB_ACTION_REF,GITHUB_ACTION_REPOSITORY,GITHUB_ACTOR,GITHUB_API_URL,GITHUB_BASE_REF,GITHUB_ENV,GITHUB_EVENT_NAME,GITHUB_EVENT_PATH,GITHUB_GRAPHQL_URL,GITHUB_HEAD_REF,GITHUB_JOB,GITHUB_PATH,GITHUB_REF,GITHUB_REPOSITORY,GITHUB_REPOSITORY_OWNER,GITHUB_RETENTION_DAYS,GITHUB_RUN_ID,GITHUB_RUN_NUMBER,GITHUB_SERVER_URL,GITHUB_SHA,GITHUB_WORKFLOW,GITHUB_WORKSPACE
            INTROSPECTION=DIFF_BRANCH,DIFF_FILES,DIFF_DIRS
            introspect=LABELS
            specific=DIFF_FORMULA
            '
