name: steptests
on: [workflow_dispatch]
jobs:
  inspect-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: test_script
        id: test_script
        run: ./.github/scripts/testing.sh
        shell: bash

      - name: action_data
        id: action_data_1
        run: ./.github/scripts/action_data.sh
        shell: bash

      - name: show_env
        id: show_env
        run: ./.github/scripts/show_env.sh
        shell: bash
        env:
          INSPECT_GROUPS: '
              git=GITHUB_ACTION,GITHUB_ACTIONS,GITHUB_ACTION_REF,GITHUB_ACTION_REPOSITORY,GITHUB_ACTOR,GITHUB_API_URL,GITHUB_BASE_REF,GITHUB_ENV,GITHUB_EVENT_NAME,GITHUB_EVENT_PATH,GITHUB_GRAPHQL_URL,GITHUB_HEAD_REF,GITHUB_JOB,GITHUB_PATH,GITHUB_REF,GITHUB_REPOSITORY,GITHUB_REPOSITORY_OWNER,GITHUB_RETENTION_DAYS,GITHUB_RUN_ID,GITHUB_RUN_NUMBER,GITHUB_SERVER_URL,GITHUB_SHA,GITHUB_WORKFLOW,GITHUB_WORKSPACE
              reference=EXISTING_LABELS,CHECK_CREATE_LABELS,KEYS_NOT_IN_SET
            '

      #- name: action_data
        #id: action_data_2
        #run: ./.github/scripts/action_data.sh
        #shell: bash
