name: steptests
on: [workflow_dispatch]
jobs:
  inspect-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: test_script
        id: test_script
        run: ./.github/scripts/testing.sh
        shell: bash

      - name: action_data
        id: action_data_1
        run: ./.github/scripts/action_data.sh
        shell: bash

      - name: action_data
        id: action_data_2
        run: ./.github/scripts/action_data.sh
        shell: bash
