name: tagger
on: [pull_request]
jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: samspills/assign-pr-to-author@v1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
        # if: github.event_name == 'pull_request' && github.event.action == 'opened'

  assign-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Get PR ID
      - name: action_data
        id: action_data
        run: ./.github/scripts/action_data.sh
        shell: bash

      # Get various changes from the PR commits
      - name: diff
        id: diff
        run: ./.github/scripts/diff_files.sh
        shell: bash

      - name: label_pr    # Attach labels to the pr where $ID = The PR ID
        run: ./.github/scripts/label_pr.sh
        shell: bash
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS: ${{ steps.diff.outputs.DIFF_ADD_LABEL_SET }}
          ID: ${{ steps.action_data.outputs.ID }}
